[package]
name = "sowngwala"
version = "0.4.0"
authors = ["Hiroki Minagawa <minagawa@tokyo800.jp>"]
edition = "2018"
publish = false

[dependencies]
serde = { version = "1.0.127", features = ["derive"] }

[dev-dependencies]
approx_eq = "0.1.8"
