[package]
name = "sowngwala"
version = "0.7.0"
authors = ["minagawah <minag@tokyo800.jp>"]
edition = "2018"
publish = false

[dependencies]
chrono = "0.4.19"
serde = { version = "1.0.127", features = ["derive"] }

[dev-dependencies]
approx_eq = "0.1.8"
